// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn_JiqrkJvFO5lBApzDTGIvhpgZ48-JXk',
    appId: '1:816627658336:web:872228bba00a439187dd05',
    messagingSenderId: '816627658336',
    projectId: 'visionmate-75ca4',
    authDomain: 'visionmate-75ca4.firebaseapp.com',
    storageBucket: 'visionmate-75ca4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9LYwfK4gMluNxOTX8qPYh07rHS7vYAP4',
    appId: '1:816627658336:android:680d1929ec74effc87dd05',
    messagingSenderId: '816627658336',
    projectId: 'visionmate-75ca4',
    storageBucket: 'visionmate-75ca4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYqovwZz9WKL-XFrLA8wFrX3Og7lKgmUo',
    appId: '1:816627658336:ios:2e64994caaf4f8e387dd05',
    messagingSenderId: '816627658336',
    projectId: 'visionmate-75ca4',
    storageBucket: 'visionmate-75ca4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYqovwZz9WKL-XFrLA8wFrX3Og7lKgmUo',
    appId: '1:816627658336:ios:2e64994caaf4f8e387dd05',
    messagingSenderId: '816627658336',
    projectId: 'visionmate-75ca4',
    storageBucket: 'visionmate-75ca4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn_JiqrkJvFO5lBApzDTGIvhpgZ48-JXk',
    appId: '1:816627658336:web:7a73fafc2abdcd7c87dd05',
    messagingSenderId: '816627658336',
    projectId: 'visionmate-75ca4',
    authDomain: 'visionmate-75ca4.firebaseapp.com',
    storageBucket: 'visionmate-75ca4.firebasestorage.app',
  );
}
